### PR TITLE
Paint docs in Brocade colors

### PR DESCRIPTION
**Pull request by enykeev**
screen shot 2016-08-22 at 5 55 02 pm

### CODE REVIEW

**Comment by emedvedev** [comment]
1. Shouldn't it say BWC instead?
2. I like the colors, but I thought the assumption was "Brocade colors == red." @LindsayHill?
Looks very nice overall.

**Comment by LindsayHill** [comment]
@emedvedev There's a whole palette of colours. Red is a dominant colour, but it's not the only one.

**Comment by emedvedev** [comment]
Alright, but seeing as you're the senior brocade color scheme expert here, I'll leave it up to you to decide. :) To me it looks pretty good.

**Comment by LindsayHill** [comment]
I'm the worst choice for deciding on a 'pretty' colour scheme, since I'm colour-deficient. All I can comment on is "Is this choice of colour still readable for people like me?"

**Comment by dzimine** [comment]
Reviewed, discussed with @enykeev, agreed to:
* StackStorm -> Brocade Workflow Composer \n Powered by [StackStorm](https://github.com/StackStorm/st2)
* search box - redo - @enykeev knows how
* remove `Dual` font
* reduce vertical size of the header (especially bottom margin under search "baseline"
* color the next/prev buttons
* favicon (one way is to re-paint st2 favicon in BRCD colors)

Other comment - more to @emedvedev likely...
- fact that we keep the alternative skin in the app seems wrong: when we have multiple apps, which one will keep the skin? OK to punt it for later (but file a bug to track if agree)

**Comment by emedvedev** [comment]
> fact that we keep the alternative skin in the app seems wrong: when we have multiple apps, which one will keep the skin?
We'll let all of them keep the skin. Another approach would be to place the skin into st2docs, have an "enterprisey" flag in conf.py, and if some app overwrites it, then change the skin accordingly. In my opinion, that would make enterprise-only includes easier as well, but we discussed it in another PR and went with a different approach, so I'm fine with patching CSS.

**Pull request merged**
